services:
  web:
    build:
      context: .
      dockerfile: Prod.Dockerfile
    command: gunicorn django_jardin.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
        - DATABASE=postgres
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
volumes:
  postgres_data: