services:
  web:
    build:
      context: .
      dockerfile: app/Prod.Dockerfile
    command: gunicorn django_jardin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
      - DATABASE=postgres
    depends_on:
      - db
      - signal

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      -
  signal:
    image: bbernhard/signal-cli-rest-api:latest
    volumes:
      - signal_data:/home/.local/share/signal-cli
    ports:
      - "8080:8080" # REST API port
    environment:
      - MODE=normal
      - AUTO_RECEIVE_SCHEDULE=0 22 * * *

volumes:
  postgres_data:
  static_volume:
  signal_data:
