services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/django_jardin/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_jardin
      - POSTGRES_PASSWORD=django_jardin
      - POSTGRES_DB=django_jardin
volumes:
  postgres_data: