services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
      - signal_data:/root/.config/signal-cli

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - signal
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_jardin
      - POSTGRES_PASSWORD=django_jardin
      - POSTGRES_DB=django_jardin
  signal:
    image: bbernhard/signal-cli-rest-api:latest
    volumes:
      - signal_data:/home/.local/share/signal-cli
    ports:
      - "8080:8080" # REST API port
    environment:
      - MODE=normal

volumes:
  postgres_data:
  signal_data: