services:
  web:
    build:
      context: .
      dockerfile: app/Prod.Dockerfile
    command: gunicorn django_jardin.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    environment:
      - DATABASE=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  letsencrypt:
