# Generated by Django 5.2.1 on 2025-05-20 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jardin_data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="sensor",
        ),
        migrations.DeleteModel(
            name="Sensor",
        ),
    ]
