# Generated by Django 5.2.1 on 2025-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jardin_data", "0002_remove_sensordata_sensor_delete_sensor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="sensordata",
            name="sensor_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="sensor_type",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
