# Generated by Django 5.2.1 on 2025-05-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jardin_data", "0003_sensordata_location_sensordata_sensor_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensordata",
            name="location",
        ),
        migrations.AddField(
            model_name="sensordata",
            name="sensor_id",
            field=models.CharField(default="", max_length=24),
            preserve_default=False,
        ),
    ]
