# Generated by Django 5.2.1 on 2025-08-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jardin_data", "0004_remove_sensordata_location_sensordata_sensor_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensordata",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="sensordata",
            name="device_id",
            field=models.CharField(default="000000000000000000000000", max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="sensor_id",
            field=models.CharField(max_length=128),
        ),
    ]
