# Generated by Django 5.2.1 on 2025-11-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jardin_data", "0005_alter_sensordata_options_sensordata_device_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sensordata",
            options={},
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["sensor_id", "-created_at"],
                name="jardin_data_sensor__d581a2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(
                fields=["created_at"], name="jardin_data_created_da8817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sensordata",
            index=models.Index(fields=["value"], name="jardin_data_value_b04865_idx"),
        ),
    ]
