name: Build, Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file for build
        run: |
          cat << 'EOF' > .env.prod
          ${{ secrets.ENV_PROD_FILE }}
          EOF

      # Add this step to set up Docker Compose
      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1
        with:
          version: v2.23.3

      - name: Build containers
        run: docker-compose -f docker-compose.prod.yml build

      - name: Run tests
        run: |
          docker-compose -f docker-compose.prod.yml run --rm web python manage.py test

      - name: Save Docker images
        if: success()
        run: |
          mkdir -p images
          docker save $(docker images -q) -o images/docker-images.tar

      - name: Upload Docker images as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: images/docker-images.tar
          retention-days: 1

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Docker images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: images

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Copy and deploy
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          set -euo pipefail    # propagate the *real* failing line
          
          echo "Transferring Docker artifacts…"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" images/docker-images.tar \
                $SERVER_USER@$SERVER_IP:/tmp/
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" docker-compose.prod.yml \
                $SERVER_USER@$SERVER_IP:/tmp/
          
          echo "Executing remote deployment…"
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP /bin/bash <<'REMOTE'
            set -euo pipefail
          
            # Stop existing stack (ignore error if first deploy)
            docker compose -f /opt/django-jardin/docker-compose.prod.yml down --remove-orphans || true
          
            # Load new images
            docker load -i /tmp/docker-images.tar
          
            # Prepare directory
            mkdir -p /opt/django-jardin
            mv /tmp/docker-compose.prod.yml /opt/django-jardin/
          
            # Write .env
            cat > /opt/django-jardin/.env.prod <<'EOF'
            ${{ secrets.ENV_PROD_FILE }}
            EOF
            
            # Start containers
            docker compose -f /opt/django-jardin/docker-compose.prod.yml up -d
            
            rm -f /tmp/docker-images.tar
            REMOTE
